version: "3.8"

services:
  trainer:
    build: .
    volumes:
      - .:/project
      - /mnt/data-8tb:/mnt/data-8tb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "1"
              capabilities: [gpu]
